export const ADD_BLOCK = "ADD_BLOCK"
export const CHNAGE_BLOCK_STYLES = "CHNAGE_BLOCK_STYLES"
export const CHNAGE_BLOCK_ATTR = "CHNAGE_BLOCK_ATTR"
export const DELETE_BLOCK = "DELETE_BLOCK"

export const ADD_SCENE = "ADD_SCENE"
export const DELETE_SCENE = "DELETE_SCENE"
export const CHANGE_SCENE_URL = "CHANGE_SCENE_URL"

export const CHANGE_CUR_SCENE = "CHANGE_CUR_SCENE"
export const CHANGE_CUR_BLOCK = "CHANGE_CUR_BLOCK"
